# Generated by Django 3.1.5 on 2021-01-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor', models.BigIntegerField(verbose_name='phone_number')),
                ('message', models.TextField()),
            ],
        ),
    ]
